### ISSUE TITLE
panic when stopping service when duplicate routes are registered

### ISSUE THREAD

**Issue by KevM** [lesismal/arpc#61]
After the updating to v1.2.15 we started getting the panic below. I erroneously was registering multiple handlers for the same route. This panic seems to be when the `arpc.Server` is stopping.

My architecture was calling `srv.Handler.Handle("duplicated/route", func...)` with the same route string a few times because of a copy paste error on my part.

The improper registration was my fault but the panic didn't seem the best way to realize this. I would prefer to have a panic immediately result from the `Handle` call with a duplicate route. If you support multiple handlers at the same route then there may be a different bug.
 
```
panic: handler exist for method /order/subscribe 
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x105147154]

goroutine 1 [running]:
github.com/lesismal/arpc.(*Server).Stop(0x14000147650)
	/Users/kevm/go/pkg/mod/github.com/lesismal/arpc@v1.2.15/server.go:113 +0x54
gitlab.com/neomantra/nimble/internal/stream.(*WebSocketServer).Stop(0x1400047db00)
	/Users/kevm/neomantra/nimble/internal/stream/websocket_server.go:25 +0x2c
panic({0x10557aa00?, 0x1400003d430?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:770 +0x124
github.com/lesismal/arpc.(*handler).handle(0x14000000b40, {0x105337336, 0x10}, 0x14000199530, {0x0, 0x0, 0x1?})
	/Users/kevm/go/pkg/mod/github.com/lesismal/arpc@v1.2.15/handler.go:594 +0x3c4
github.com/lesismal/arpc.(*handler).Handle(0x1400045a280?, {0x105337336?, 0x2?}, 0x0?, {0x0?, 0x0?, 0x140000180d0?})
	/Users/kevm/go/pkg/mod/github.com/lesismal/arpc@v1.2.15/handler.go:565 +0x28
gitlab.com/neomantra/nimble/internal/stream.RegisterStreamWithWebSocket[...](0x14000147650, {0x105703d00, 0x14000016168}, 0x1400045a280)
	/Users/kevm/neomantra/nimble/internal/stream/stream.go:45 +0x268
```

**Comment by lesismal** [comment]
Thank you for your feedback!
Would you please provide the full example that can reproduce the panic?

**Comment by lesismal** [comment]
According to the panic log, I guess it's like this:
```golang
package main

import (
	"os"
	"os/signal"
	"syscall"

	"github.com/lesismal/arpc"
)

func handler(ctx *arpc.Context) {
	ctx.Write("hello")
}

func main() {
	server := arpc.NewServer()
	defer server.Stop() // This will be called before main func exit

	// register this method first time.
	server.Handler.Handle("/yourMethod", handler)

	// Register for the same method and cause that panic,
	// then the main func will return and the server.Stop() will be called before the main func exit.
	// Because the server haven't called server.Run(addr) or server.Serve(ln), it doesn't have a listener,
	// so it panic again because the server.Stop() has a log using the listener.Addr
	server.Handler.Handle("/yourMethod", handler)

	go server.Run("localhost:8888")

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
}
```

And I got the same panic log:
```sh
server.go:10:2: no required module provides package github.com/henrylee2cn/goutil/graceful; to add it:
	go get github.com/henrylee2cn/goutil/graceful
lesismal@192 server % go run ./server.go
panic: handler exist for method /yourMethod 
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100c19084]

goroutine 1 [running]:
github.com/lesismal/arpc.(*Server).Stop(0x1400013e000)
	/Users/lesismal/dev/gopath/pkg/mod/github.com/lesismal/arpc@v1.2.15/server.go:113 +0x54
panic({0x100c61f20?, 0x1400011a130?})
	/Users/lesismal/dev/go/src/runtime/panic.go:914 +0x218
github.com/lesismal/arpc.(*handler).handle(0x1400013a120, {0x100c1c533, 0xb}, 0x100c86d00, {0x0, 0x0, 0x1400013a120?})
	/Users/lesismal/dev/gopath/pkg/mod/github.com/lesismal/arpc@v1.2.15/handler.go:594 +0x3c4
github.com/lesismal/arpc.(*handler).Handle(0x14000062ec8?, {0x100c1c533?, 0x140000526e8?}, 0x100b34750?, {0x0?, 0x140000021a0?, 0x14000062f28?})
	/Users/lesismal/dev/gopath/pkg/mod/github.com/lesismal/arpc@v1.2.15/handler.go:565 +0x28
main.main()
	/Users/lesismal/Desktop/lesismal/arpc/examples/graceful/server/server.go:26 +0xc4
exit status 2
```

Please fix your handler registration and try it again, if the problem is still there, please try the previous version of arpc you used. If the problem not gone, please provide me a full example that can reproduce it and I will try it.

**Comment by KevM** [comment]
Ah I see that I didn't follow the stack trace well enough. Sorry to waste your time. Everything seems fine. I have an elaborate handler setup because I have an abstraction layer over ARPC to supporting plugging in different stream sources. I was assuming my problem was novel because of this. I guess it was not.
